### ISSUE TITLE
How to run model on given MOF?

### ISSUE THREAD

**Issue by vthost** [Sangwon91/MOF-NET#1]
Thank you for providing the code!! I also had a look at POREMAKE but am not fully sure how to run the model on, e.g., a MOF from CoRE. The paper's supplementary provides the description of how you deconstructed the MOFs, therefore I wonder if the code is available somewhere (I might well have missed the method...).

**Comment by Sangwon91** [comment]
Hello, vthost. It's been a long time since I graduated, so I think I need to look for it.

**Comment by Sangwon91** [comment]
I've added the training notebook and inputs in the `examples` folder. However, unfortunately, I couldn't find the MOF destruction code...

**Comment by vthost** [comment]
Ok, that's unlucky.. but Thank you for checking!
